### ISSUE TITLE
висота і небезпека переповнення

### ISSUE THREAD

**Issue by pecourses** [ArtyomHloba/project-1-CSS#2]
https://github.com/ArtyomHloba/project-1-CSS/blob/8ab6567ca7c697d2a3fb1c3132fd6c7ec34ff277/accets/css/style.css#L63
- забігаючи наперед, висоту варто задавати тільки декоратисним елементам, наприклад, зображенням, елементам з зображенням на тлі тощо. Інакше виникає небезпека переповнення (звузьте вьюпорт до 320px і подивіться, як текст вилізе за межі свого блоку вниз). 
![image](https://github.com/ArtyomHloba/project-1-CSS/assets/67504221/e8024f90-058b-4ddf-8616-b2c1e3c4376b)
Тому зазвичай висота текстових блоків формується за допомогою безпосередньо контенту (тексту) та _**падінгів**_, тоді  (без обмеження висоти) блок буде автоматично адаптуватися під той контент, який в ньому є:
![image](https://github.com/ArtyomHloba/project-1-CSS/assets/67504221/58601303-781a-4af5-9384-06f91162d66b)

**Comment by ArtyomHloba** [comment]
Понял свои ошибку, в след коммите фиксану, а по поводу высоты, хотел просто прикинуть как будет у меня это выглядеть, так что я уберу пока что какую либо высоту и ширину(тоже в некст коммите).

**Comment by pecourses** [comment]
Так, це дійсно класний і результативний підхід, пробувати як що працює 👍
